### ISSUE TITLE
Plugin is incompatible with MantisBT version 2.25.x

### ISSUE THREAD

**Issue by AlainWsk** [nenes25/mantisbt_autosuggest#7]
Hello,
We are interested by this plugin, but its installation fails because our MantisBT version is 2.25.x
Could it be possible to allow newer MantisBT releases ?
I add a quick look at the code, and it seems that the code checks that Mantis version is 2.2.x (I am not a PHP expert, though)

Thanks

**Comment by nenes25** [comment]
Hello,
This plugin is quite old,I'll check next week and let you know.

Regards,

**Comment by nenes25** [comment]
Hello,

In fact the issue is not related with the mantis version which is well compatible.
But with the fact that you need to install the JqueryUi Widget ( on which this module rely )
I manage to install the module with no issue on the last mantis version once it is done.
![image](https://user-images.githubusercontent.com/7163132/227859954-23fca0f7-3676-4fb1-810e-6b1886498c7e.png)

The jQuery Ui widget can be downloaded here : https://github.com/mantisbt-plugins/jQuery-UI

Regards,

**Comment by AlainWsk** [comment]
Thanks, this solves the issue !
